spring.application.name=backend_syndic

# JPA settings (Shared logic)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Default Profile Activation
# This tells the app to look for 'application-dev.properties'
spring.profiles.active=dev